version: '3.4'

services:
  postgres-login-jwt:
    container_name: postgres-login-jwt
    image: postgres:13-alpine
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pg-login"
    ports: 
      - "5432:5432"