version: '3.4'

services:
  your-service-name:
    container_name: your-container-name
    image: postgres:13-alpine
    volumes:
      - ./.vscode/postgres-data/:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "your-postgres-password"
      POSTGRES_DB: "your-database-name"
    ports: 
      - "5432:5432"